apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-student-management-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: my-student-management-api
  replicas: 2
  template:
    metadata:
      labels:
        app: my-student-management-api
    spec:
      containers:
        - name: my-student-management-api
          image: IMAGE_URI
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: connection-string
---
apiVersion: v1
kind: Service
metadata:
  name: my-student-management-api-service
spec:
  selector:
    app: my-student-management-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP