services:
  database:
    image: mongo:5.0
    container_name: "my-student-db"
    ports:
      - 27017:27017
  api:
    build:
      context: spring-boot-student-app-api
      dockerfile: Dockerfile
    container_name: "my-student-api"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - MONGO_URL=mongodb://database:27017/my_student_db
    ports:
      - "8080:8080"
  web:
    build:
      context: react-student-management
      dockerfile: Dockerfile
    container_name: "my-student-web"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    ports:
      - "3000:3000"
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
