apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app-client
  namespace: default
spec:
  selector:
    matchLabels:
      app: student-app-client
  replicas: 2
  template:
    metadata:
      labels:
        app: student-app-client
    spec:
      containers:
        - name: student-app-client
          image: IMAGE_URI
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://student-app-api-service:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: student-app-client-service
spec:
  selector:
    app: student-app-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: student-app-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: student-app-api-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: student-app-client-service
                port:
                  number: 80